### ISSUE TITLE
Suggestion: commit a `yarn.lock` so dependencies can locked down to a specific version

### ISSUE THREAD

**Issue by khushkaranbajwa** [KhalisFoundation/hukamnama-json#8]
Kinda self-explanatory... didn't wanna open a PR for it in case anybody was massively opposed to yarn!

**Comment by Harjot1Singh** [comment]
Why not use the `package-lock.json` generated in npm 5+?

**Comment by khushkaranbajwa** [comment]
Agreed, hence why I didn't PR - wow around 2 years ago... I'll close this :)
